export { babelLoader } from './babel-loader'
export { assetLoader } from './asset-loader'
export { cssLoader } from './css-loader'
export { fontsLoader } from './fonts-loader'
export { svgLoader } from './svg-loader'
