export { allowedOrigins } from './allowedOrigins'
export { corsOptions } from './corsOptions'
export { startServer, closeServer } from './server'
export { uri, clientOptions } from './dbSettings'
export { runDB } from './runDB'
