export { allowedOrigins } from './allowedOrigins'
export { corsOptions } from './corsOptions'
export { startServer } from './startServer'
export { uri, clientOptions } from './dbSettings'
export { runDB } from './runDB'
